apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deploy
  labels:
    app: registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: registry-container
        image: gcr.io/emrys-12/registry:latest
        resources:
          requests:
            cpu: 50m
            memory: "100Mi"
          # limits:
          #   cpu: 250m
          #   memory: "500Mi"
        ports:
        - containerPort: 5000
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret
        - name: DBNAME
          value: "emrysserver"
        - name: DBNETLOC
          value: "sqlproxy-svc"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DBPORT
          value: "5432"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/google_application_credentials/credentials.json"
        - name: DEBUG_CORS
          value: "false"
        - name: REGISTRY_HOST
          value: "127.0.0.1:5001"
        volumeMounts:
          - name: registry-creds
            mountPath: /secrets/google_application_credentials
            readOnly: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      - name: registry
        image: registry:2
        args: [ "/etc/docker/registry/registry-config.yaml" ]
        resources:
          requests:
            cpu: 100m
            memory: "500Mi"
          # limits:
          #   cpu: 500m
          #   memory: "2Gi"
        ports:
        - containerPort: 5001
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: secret
        # - name: REGISTRY_LOG_LEVEL
        #   value: "DEBUG"
        - name: REGISTRY_LOG_FIELDS_ENVIRONMENT
          value: "production"
        volumeMounts: 
          - name: registry-creds
            mountPath: /secrets/google_application_credentials
            readOnly: true
          - name: registry-config
            mountPath: /etc/docker/registry
      volumes:
      - name: registry-creds
        secret:
          secretName: registry-creds
      - name: registry-config
        configMap:
          name: registry-registry-config
