steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/default-backend/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/default-backend:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/default-backend:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/auth/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/auth:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/auth:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/user/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/user:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/user:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/miner/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/miner:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/miner:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/job/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/job:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/job:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/notebook/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/notebook:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/notebook:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/notebook/dockerfile-sshd',
    '-t', 'gcr.io/$PROJECT_ID/notebook-sshd:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/notebook-sshd:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/image/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/image:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/image:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/registry/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/registry:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/registry:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/data/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/data:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/data:latest',
    '.' ]
images: [
  'gcr.io/$PROJECT_ID/default-backend:$_BUILD', 'gcr.io/$PROJECT_ID/default-backend:latest',
  'gcr.io/$PROJECT_ID/auth:$_BUILD', 'gcr.io/$PROJECT_ID/auth:latest',
  'gcr.io/$PROJECT_ID/user:$_BUILD', 'gcr.io/$PROJECT_ID/user:latest',
  'gcr.io/$PROJECT_ID/miner:$_BUILD', 'gcr.io/$PROJECT_ID/miner:latest',
  'gcr.io/$PROJECT_ID/job:$_BUILD', 'gcr.io/$PROJECT_ID/job:latest',
  'gcr.io/$PROJECT_ID/notebook:$_BUILD', 'gcr.io/$PROJECT_ID/notebook:latest',
  'gcr.io/$PROJECT_ID/notebook-sshd:$_BUILD', 'gcr.io/$PROJECT_ID/notebook-sshd:latest',
  'gcr.io/$PROJECT_ID/image:$_BUILD', 'gcr.io/$PROJECT_ID/image:latest',
  'gcr.io/$PROJECT_ID/registry:$_BUILD', 'gcr.io/$PROJECT_ID/registry:latest',
  'gcr.io/$PROJECT_ID/data:$_BUILD', 'gcr.io/$PROJECT_ID/data:latest',
]
tags: [ 'default-backend', 'auth', 'user', 'miner', 'job', 'notebook', 'notebook-sshd', 'image', 'registry', 'data', '$_BUILD' ]
