steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'pull', 'gcr.io/$PROJECT_ID/emrysserver:latest' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/emrysserver',
        # '--cache-from', 'gcr.io/$PROJECT_ID/emrysserver:latest',
        '.'
        ]
images:
  - 'gcr.io/$PROJECT_ID/emrysserver:latest'
