steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/user/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/user:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/user:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/miner/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/miner:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/miner:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/job/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/job:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/job:latest',
    '.' ]
images: [
  'gcr.io/$PROJECT_ID/user:$_BUILD', 'gcr.io/$PROJECT_ID/user:latest',
  'gcr.io/$PROJECT_ID/miner:$_BUILD', 'gcr.io/$PROJECT_ID/miner:latest',
  'gcr.io/$PROJECT_ID/job:$_BUILD', 'gcr.io/$PROJECT_ID/job:latest'
]
tags: [ 'user', 'miner', 'job', '$_BUILD' ]
