steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/user/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/user:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/user:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/miner/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/miner:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/miner:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/job/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/job:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/job:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/image/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/image:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/image:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/registry/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/registry:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/registry:latest',
    '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/data/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/data:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/data:latest',
    '.' ]
images: [
  'gcr.io/$PROJECT_ID/user:$_BUILD', 'gcr.io/$PROJECT_ID/user:latest',
  'gcr.io/$PROJECT_ID/miner:$_BUILD', 'gcr.io/$PROJECT_ID/miner:latest',
  'gcr.io/$PROJECT_ID/job:$_BUILD', 'gcr.io/$PROJECT_ID/job:latest',
  'gcr.io/$PROJECT_ID/image:$_BUILD', 'gcr.io/$PROJECT_ID/image:latest',
  'gcr.io/$PROJECT_ID/registry:$_BUILD', 'gcr.io/$PROJECT_ID/registry:latest',
  'gcr.io/$PROJECT_ID/data:$_BUILD', 'gcr.io/$PROJECT_ID/data:latest',
]
tags: [ 'user', 'miner', 'job', 'image', 'registry', 'data', '$_BUILD' ]
