apiVersion: v1
kind: Pod
metadata:
  name: emrysserver-pod
  labels:
    app: emrysserver
spec:
  containers:
  - name: emrysserver-container
    image: gcr.io/emrys-12/emrysserver
    env:
    - name: DBNAME
      value: "emrysuser"
    - name: DBNETLOC
      value: "localhost"
    - name: DBPASSWORD
      valueFrom:
        secretKeyRef:
          name: emrysserver-secret
          key: dbpassword
    - name: DBPORT
      value: "5432"
    - name: DBUSER
      valueFrom:
        secretKeyRef:
          name: emrysserver-secret
          key: dbuser
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
    - name: emrys-volume
      mountPath: /data
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: ["/cloud_sql_proxy",
              "-instances=emrys-12:us-central1:emrysserver-psql=tcp:5432"]
    volumeMounts:
      - name: cloudsql-instance-credentials
        mountPath: /secrets/cloudql
        readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: emrysserver-secret
  - name: emrys-volume
    gcePersistentDisk:
      pdName: emrys-disk
      fsType: ex4
