apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emrys-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "emrys-static-ip"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: emrys-tls-secret
  rules:
  - host: emrys.io
    http:
      paths:
      - backend:
          serviceName: emrys-svc
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: emrys-svc
  labels:
    app: emrys
spec:
  selector:
    app: emrys
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emrys-deployment
  labels:
    app: emrys
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: emrys
  template:
    metadata:
      labels:
        app: emrys
    spec:
      restartPolicy: Always
      containers:
      - name: emrys-container
        image: gcr.io/emrys-12/emrysserver
        ports:
        - containerPort: 8080
        env:
        - name: DBNAME
          value: "emrysserver"
        - name: DBNETLOC
          value: "localhost"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DBPORT
          value: "5432"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: MINERSECRET
          valueFrom:
            secretKeyRef:
              name: miner-secret
              key: secret
        - name: USERSECRET
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: secret
        # volumeMounts:
        # - name: emrys-volume
        #   mountPath: /data
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=emrys-12:us-central1:emrysserver-psql=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      # - name: emrys-volume
      #   gcePersistentDisk:
      #     pdName: emrys-disk
      #     fsType: ex4
