FROM golang:1.9.2-alpine
COPY . /go/src/github.com/wminshew/emrysserver/cmd/traefik
RUN go install github.com/wminshew/emrysserver/cmd/traefik

FROM alpine:3.8
RUN apk --update upgrade && \
  apk add curl ca-certificates && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
COPY --from=0 /go/bin/traefik .
CMD ["./traefik"]
