FROM golang:1.11.2-alpine as builder
COPY . /go/src/github.com/wminshew/emrysserver
RUN go install github.com/wminshew/emrysserver/cmd/image

FROM alpine:3.8
RUN apk --update upgrade && \
  apk add curl ca-certificates && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
COPY --from=builder /go/bin/image .
CMD ["./image"]
