apiVersion: v1
kind: Service
metadata:
  name: miner-svc
  labels:
    app: miner
spec:
  selector:
    app: miner
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner-deploy
  labels:
    app: miner
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: miner
  template:
    metadata:
      labels:
        app: miner
    spec:
      restartPolicy: Always
      containers:
      - name: miner-container
        image: gcr.io/emrys-12/miner
        resources:
          requests:
            cpu: 100m
            memory: "200Mi"
          # limits:
          #   cpu: 250m
          #   memory: "500Mi"
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/google_application_credentials/credentials.json"
        - name: DBNAME
          value: "emrysserver"
        - name: DBNETLOC
          value: "sqlproxy-svc"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DBPORT
          value: "5432"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DEBUG_CORS
          value: "false"
        - name: DEBUG_LOG
          value: "false"
        - name: DEBUG_LONGPOLL
          value: "false"
        - name: MINER_SEMVER
          value: "0.5.0"
        - name: MINER_TIMEOUT
          value: "120"
        - name: SENDGRID_SECRET
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-keys
              key: secret-key
        volumeMounts:
          - name: miner-creds
            mountPath: /secrets/google_application_credentials
            readOnly: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: miner-creds
        secret:
          secretName: miner-creds
