apiVersion: v1
kind: Service
metadata:
  name: miner-svc
  labels:
    app: miner
  namespace: emrys-prod
  annotations:
    # cloud.google.com/neg: '{"ingress": true}' # container-native load balancing
    beta.cloud.google.com/backend-config: '{"ports": {"http":"miner-backendconfig"}}'
    # cloud.google.com/app-protocols: '{"http": "HTTP2"}'
spec:
  selector:
    app: miner
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: miner-backendconfig
  namespace: emrys-prod
spec:
  balancingMode: UTILIZATION
  timeoutSec: 620
  connectionDraining:
    drainingTimeoutSec: 630
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner-deploy
  labels:
    app: miner
  namespace: emrys-prod
spec:
  minReadySeconds: 60
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: miner
  template:
    metadata:
      labels:
        app: miner
    spec:
      terminationGracePeriodSeconds: 630
      restartPolicy: Always
      containers:
      - name: miner-container
        image: gcr.io/emrys-12/miner
        securityContext:
          runAsUser: 2 # non-root
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['all']
        resources:
          requests:
            cpu: 200m
            memory: "400Mi"
          limits:
            cpu: 200m
            memory: "400Mi"
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/google_application_credentials/credentials.json"
        - name: DB_NAME
          value: "emrysserver"
        - name: DB_NETLOC
          value: "sqlproxy-svc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DEBUG_CORS
          value: "false"
        - name: DEBUG_LOG
          value: "false"
        - name: DEBUG_LONGPOLL
          value: "false"
        - name: MINER_SEMVER
          value: "0.6.3"
        - name: MINER_TIMEOUT
          value: "120"
        - name: SENDGRID_SECRET
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-keys
              key: secret-key
        volumeMounts:
          - name: miner-creds
            mountPath: /secrets/google_application_credentials
            readOnly: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: miner-creds
        secret:
          secretName: miner-creds
