apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"app":"devpi"},"name":"devpi-pv","namespace":""},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"claimRef":{"apiVersion":"v1","kind":"PersistentVolumeClaim","name":"devpi-pvc-devpi-sts-0","namespace":"default"},"gcePersistentDisk":{"fsType":"ext4","pdName":"gke-emrys-9c80fd71-dyn-pvc-45c20220-972e-11e8-b365-42010a800192"},"storageClassName":"standard"}}
  creationTimestamp: 2018-08-23T18:57:03Z
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: devpi
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-a
  name: devpi-pv
  resourceVersion: "52230506"
  selfLink: /api/v1/persistentvolumes/devpi-pv
  uid: 52abb8be-a706-11e8-86e5-42010a800040
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-emrys-9c80fd71-dyn-pvc-45c20220-972e-11e8-b365-42010a800192
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
status:
  phase: Available
