apiVersion: v1
kind: Service
metadata:
  name: devpi-svc
  labels:
    app: devpi
  namespace: emrys-prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # container-native load balancing
    beta.cloud.google.com/backend-config: '{"ports": {"http":"devpi-backendconfig"}}'
spec:
  selector:
    app: devpi
  type: NodePort
  ports:
  - name: http
    port: 3141
    targetPort: 3141
    protocol: TCP
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: devpi-backendconfig
  namespace: emrys-prod
spec:
  timeoutSec: 320
  connectionDraining:
    drainingTimeoutSec: 330
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devpi-sts
  labels:
    app: devpi
  namespace: emrys-prod
spec:
  replicas: 1
  serviceName: "devpi-svc"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: devpi
  template:
    metadata:
      labels:
        app: devpi
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: devpi-container
        image: gcr.io/emrys-12/devpi:latest
        securityContext:
          # runAsUser: 2 # non-root
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['all']
        resources:
          requests:
            cpu: 500m
            memory: "1Gi"
          limits:
            cpu: 500m
            memory: "1Gi"
        ports:
        - containerPort: 3141
        env:
        - name: DEVPISERVER_MAX_RETRIES
          value: "10"
        - name: DEVPISERVER_SERVERDIR
          value: "/devpi/server"
        # - name: DEVPISERVER_DEBUG
        #   value: "true"
        volumeMounts:
          - name: devpi-pvc
            mountPath: /devpi
        readinessProbe:
          httpGet:
            path: /+api
            port: 3141
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /+api
            port: 3141
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: devpi-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi # not updateable on resize
