apiVersion: v1
kind: Service
metadata:
  name: docker-svc
  labels:
    app: docker
spec:
  selector:
    app: docker
  type: NodePort
  ports:
  - name: http
    port: 2375
    targetPort: 2375
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deploy
  labels:
    app: docker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      restartPolicy: Always
      containers:
      - name: dind-daemon 
        image: docker:18.03.1-ce-dind 
        securityContext: 
          privileged: true 
        ports:
        - containerPorts: 2375
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
      volumes:
      - name: docker-graph-storage 
        emptyDir: {}
