apiVersion: v1
kind: Service
metadata:
  name: docker-svc
  labels:
    app: docker
spec:
  selector:
    app: docker
  clusterIP: None
  ports:
  - name: dockerd
    port: 2375
    targetPort: 2375
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-stfl
  labels:
    app: docker
spec:
  serviceName: "docker-svc"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: dind-daemon 
        image: docker:18.03.1-ce-dind 
        securityContext: 
          privileged: true 
        ports:
        - containerPort: 2375
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
  volumeClaimTemplates:
  - metadata:
      name: docker-graph-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
