apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth
  namespace: emrys-prod
spec:
  selector:
    app: auth
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  labels:
    app: auth
  namespace: emrys-prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      restartPolicy: Always
      containers:
      - name: auth-container
        image: gcr.io/emrys-12/auth
        securityContext:
          runAsUser: 2 # non-root
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['all']
        resources:
          requests:
            cpu: 50m
            memory: "50Mi"
          limits:
            cpu: 50m
            memory: "50Mi"
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret
        - name: DB_NAME
          value: "emrysserver"
        - name: DB_NETLOC
          value: "sqlproxy-svc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DEBUG_CORS
          value: "false"
        - name: DEBUG_LOG
          value: "false"
        - name: NEW_USER_CREDIT
          value: "10"
        - name: SENDGRID_SECRET
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
