apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: 2018-08-22T01:52:39Z
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-a
  name: job-pv
  resourceVersion: "52230454"
  selfLink: /api/v1/persistentvolumes/pvc-0a48fc95-a5ae-11e8-86e5-42010a800040
  uid: 0cf46f23-a5ae-11e8-86e5-42010a800040
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-emrys-9c80fd71-dyn-pvc-0a48fc95-a5ae-11e8-86e5-42010a800040
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
status:
  phase: Available
