apiVersion: v1
kind: Service
metadata:
  name: job-svc
  labels:
    app: job
spec:
  selector:
    app: job
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: job-sts
  labels:
    app: job
spec:
  replicas: 1
  serviceName: "job-svc"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: job-container
        image: gcr.io/emrys-12/job
        resources:
          requests:
            cpu: 100m
            memory: "1Gi"
          # limits:
          #   cpu: 200m
          #   memory: "200Mi"
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/google_application_credentials/credentials.json"
        - name: DBNAME
          value: "emrysserver"
        - name: DBNETLOC
          value: "sqlproxy-svc"
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DBPORT
          value: "5432"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: MINER_SECRET
          valueFrom:
            secretKeyRef:
              name: miner-secret
              key: secret
        - name: USER_SECRET
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: secret
        volumeMounts:
          - name: job-creds
            mountPath: /secrets/google_application_credentials
            readOnly: true
          - name: job-pvc
            mountPath: /output
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: job-creds
        secret:
          secretName: job-creds
  volumeClaimTemplates:
  - metadata:
      name: job-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
