apiVersion: v1
kind: Service
metadata:
  name: job-svc
  labels:
    app: job
  namespace: emrys-prod
  annotations:
    # cloud.google.com/neg: '{"ingress": true}' # container-native load balancing
    beta.cloud.google.com/backend-config: '{"ports": {"http":"job-backendconfig"}}'
    cloud.google.com/app-protocols: '{"http": "HTTP2"}'
spec:
  selector:
    app: job
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: job-backendconfig
  namespace: emrys-prod
spec:
  timeoutSec: 620
  connectionDraining:
    drainingTimeoutSec: 630
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: job-sts
  labels:
    app: job
  namespace: emrys-prod
spec:
  replicas: 1
  serviceName: "job-svc"
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      terminationGracePeriodSeconds: 630
      restartPolicy: Always
      containers:
      - name: job-container
        image: gcr.io/emrys-12/job
        securityContext:
          # runAsUser: 2 # non-root
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['all']
        resources:
          requests:
            cpu: 500m
            memory: "1Gi"
          limits:
            cpu: 500m
            memory: "1Gi"
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/google_application_credentials/credentials.json"
        - name: DB_NAME
          value: "emrysserver"
        - name: DB_NETLOC
          value: "sqlproxy-svc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DEBUG_CORS
          value: "false"
        - name: DEBUG_LOG
          value: "false"
        - name: DEBUG_LONGPOLL
          value: "false"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-keys
              key: secret-key
        volumeMounts:
          - name: job-creds
            mountPath: /secrets/google_application_credentials
            readOnly: true
          - name: job-pvc
            mountPath: /output
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: job-creds
        secret:
          secretName: job-creds
  volumeClaimTemplates:
  - metadata:
      name: job-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi # not updateable on resize
