FROM wminshew/emrys:cuda9.0-cudnn7-devel-ubuntu16.04
MAINTAINER William Minshew <wminshew@gmail.com>

ARG USER

# USER user:user

WORKDIR $USER

RUN virtualenv venv
COPY requirements.txt requirements.txt
RUN venv/bin/pip install -r requirements.txt

COPY train.py train.py
CMD ["venv/bin/python", "train.py"]
