FROM wminshew/emrys:cuda9.0-base-ubuntu16.04
LABEL maintainer="William Minshew <w@emrys.io>"

ARG HOME
RUN useradd --create-home --home-dir $HOME user \
  && chown -R user:user $HOME

WORKDIR $HOME
User user

RUN virtualenv venv
COPY --chown=user:user requirements.txt requirements.txt
RUN venv/bin/pip install -r requirements.txt

COPY --chown=user:user train.py train.py
CMD ["venv/bin/python", "train.py"]
