apiVersion: v1
kind: Service
metadata:
  name: default-backend-svc
  labels:
    app: default-backend
  namespace: emrys-prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # container-native load balancing
    cloud.google.com/app-protocols: '{"http": "HTTP2"}'
spec:
  selector:
    app: default-backend
  type: NodePort
  ports:
  - name: default-backend
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend-deploy
  labels:
    app: default-backend
  namespace: emrys-prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: default-backend-container
        image: gcr.io/emrys-12/default-backend:latest
        securityContext:
          runAsUser: 2 # non-root
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['all']
        resources:
          requests:
            cpu: 50m
            memory: "50Mi"
          limits:
            cpu: 50m
            memory: "50Mi"
        ports:
        - containerPort: 8080
        env:
        - name: DB_NAME
          value: "emrysserver"
        - name: DB_NETLOC
          value: "sqlproxy-svc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DEBUG_CORS
          value: "false"
        - name: DEBUG_LOG
          value: "false"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
