steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './cmd/notebook/dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/notebook:$_BUILD',
    '-t', 'gcr.io/$PROJECT_ID/notebook:latest', '.' ]
images: [ 'gcr.io/$PROJECT_ID/notebook:$_BUILD', 'gcr.io/$PROJECT_ID/notebook:latest' ]
tags: [ 'notebook', '$_BUILD' ]
