FROM alpine:3.8
RUN apk --update upgrade && \
  apk add curl ca-certificates bash openssh && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
EXPOSE 2222

COPY ./cmd/notebook/entrypoint-sshd.sh .
RUN chmod +x ./entrypoint-sshd.sh
CMD ["./entrypoint-sshd.sh"]
