apiVersion: v1
kind: Service
metadata:
  name: notebook-svc
  labels:
    app: notebook
spec:
  selector:
    app: notebook
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-sshd-svc
  labels:
    app: notebook
spec:
  selector:
    app: notebook
  type: LoadBalancer
  loadBalancerIP: "35.202.18.216"
  ports:
  - name: ssh
    port: 2222
    targetPort: 2222
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-deploy
  labels:
    app: notebook
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: notebook-container
        image: gcr.io/emrys-12/notebook
        resources:
          requests:
            cpu: 50m
            memory: "50Mi"
        ports:
        - containerPort: 8080
        - containerPort: 2222
        env:
        - name: DB_NAME
          value: "emrysserver"
        - name: DB_NETLOC
          value: "sqlproxy-svc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DEBUG_LOG
          value: "false"
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: secret
        - name: SSHD_CONFIG
          value: "/etc/sshd/sshd_config"
        volumeMounts: 
          - name: notebook-sshd-config
            mountPath: /etc/sshd
            readOnly: true
          - name: ssh-host-keys
            mountPath: /etc/sshd-keys
            readOnly: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: notebook-sshd-config
        configMap:
          name: notebook-sshd-config
          defaultMode: 0600
      - name: ssh-host-keys
        secret:
          secretName: ssh-host-keys
          defaultMode: 0600
