apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user
  namespace: emrys-prod
  annotations:
    # cloud.google.com/neg: '{"ingress": true}' # container-native load balancing
    cloud.google.com/app-protocols: '{"http": "HTTP2"}'
spec:
  selector:
    app: user
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user
  namespace: emrys-prod
spec:
  minReadySeconds: 60
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: user-container
        image: gcr.io/emrys-12/user
        securityContext:
          runAsUser: 2 # non-root
          allowPrivilegeEscalation: false
          capabilities:
            drop: ['all']
        resources:
          requests:
            cpu: 50m
            memory: "100Mi"
          limits:
            cpu: 50m
            memory: "100Mi"
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: secret
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/google_application_credentials/credentials.json"
        - name: DB_NAME
          value: "emrysserver"
        - name: DB_NETLOC
          value: "sqlproxy-svc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DEBUG_CORS
          value: "false"
        - name: DEBUG_LOG
          value: "false"
        - name: STRIPE_USER_PLAN_ID
          value: "plan_EnSQKotvAnYrtO"
        - name: STRIPE_PUB_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-keys
              key: pub-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-keys
              key: secret-key
        - name: STRIPE_WEBHOOK_SECRET_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: stripe-webhook-keys
              key: account-key
        - name: STRIPE_WEBHOOK_SECRET_CONNECT
          valueFrom:
            secretKeyRef:
              name: stripe-webhook-keys
              key: connect-key
        - name: USER_SEMVER
          value: "0.6.1"
        volumeMounts:
          - name: user-creds
            mountPath: /secrets/google_application_credentials
            readOnly: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: user-creds
        secret:
          secretName: user-creds
