FROM golang:1.9.2-alpine as builder
COPY . /go/src/github.com/wminshew/emrysserver
RUN go install github.com/wminshew/emrysserver/cmd/data

FROM alpine:3.8
RUN apk --update upgrade && \
  apk add curl \
  ca-certificates \
  gcc \
  python-dev \
  py-cffi \
  py-cryptography \
  py-pip \
  py-setuptools \
  libffi-dev \
  musl-dev \
  openssl-dev \
  && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
RUN pip install --upgrade pip && \
  pip install gsutil
COPY --from=builder /go/bin/data /go-data
CMD ["/go-data"]
