apiVersion: v1
kind: Service
metadata:
  name: sqlproxy-svc
  labels:
    app: sqlproxy
spec:
  selector:
    app: sqlproxy
  type: NodePort
  ports:
  - name: http
    port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlproxy-deploy
  labels:
    app: sqlproxy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sqlproxy
  template:
    metadata:
      labels:
        app: sqlproxy
    spec:
      restartPolicy: Always
      containers:
      - name: sqlproxy-container
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
          "-instances=emrys-12:us-central1:emrysserver-psql=tcp:0.0.0.0:5432",
          "-credential_file=/secrets/cloudsql/credentials.json"]
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
